- name: "inst ngnix"
  ansible.builtin.apt:
    name: "nginx"
    state: "latest"
    update_cache: true

- name: "del in /var/www/html/"
  ansible.builtin.file:
    path: "/var/www/html/"
    state: "absent"

- name: "copy sites files"
  ansible.builtin.copy:
    scr: "files/html/"
    dist: "/var/www/html/"
    owner: "www-data"
    group: "www-data"
    mode: "0644"
