- name: "inst mysql and pymysql"
    ansible.builtin.apt:
      name: "{{ item }}"
      state: "latest"
      update_cache: true
    with_items:
      - "mysql-server"
        "python3-mymysql"

- name: "user in mysql"
    community.mysql.mysql_user:
      name: "root"
      password: "pass"
      login_user: "root"
      login_password: "pass"
      check_implicit_admin: true
      login_unix_socket: "/var/run/mysqld/mysqld.sock"

- name: "remove anonym users"
    community.mysql.mysql_user:
      name: ""
      state: "absent"
      login_user: "root"
      login_password: "pass"

- name: "remove test db"
    community.mysql.mysql_db:
      name: "test"
      state: "absent"
      login_user: "root"
      login_password: "pass"
